---
title: "Mono light theme example"
author: "Some Body"
institute: "University of Where"
format:
    mono-light-revealjs:
        theme: [default, custom.scss]
---

## Mono light

This theme is based on the xaringanthemer style "mono light": <https://pkg.garrickadenbuie.com/xaringanthemer/reference/style_mono_light.html>.

And here is some code:

```r
a <- 1 + 3
cat(a)
```

## Typography

This is *italics* and this is **bold text**.

> Just a simple quote.

---Nobody

## Dark background {background-color=var(--inverse)}

A list:

- Of my
- favourite
- things and some `code`.

```r
a <- 1 + 3
cat(a)
```

> Just a simple quote.

## Tachyons

The extension imports [Tachyons](https://tachyons.io), which can be used to design a variety of objects like the following box (see `example.qmd` for the source code).

::: {.bg-washed-blue .b--dark-blue .ba .bw2 .br3 .shadow-2 .ph4}
**This is a nice box**

- And you can
- even add some
- lists.
:::

And this Download button.

::: {.f6 .grow .no-underline .br-pill .ph3 .pv2 .mb2 .dib .white .bg-purple}
Download
:::

## Customisation

To customise the theme, you need to set `theme: [default, custom.scss]` and use `custom.scss` file, like so.

```yaml
format:
    mono-light-revealjs:
        theme: [default, custom.scss]
```

You can customise now the theme in `custom.scss`. For example, if you want to change the base colour of the theme to a green hue, add the following to the `custom.scss` file:

```scss
/*-- scss:defaults --*/
$base-color: #136f63;
```

<br>

For a list of customisable variables, see `_extensions/mono-light/mono-light.scss` and [Sass variables](https://quarto.org/docs/presentations/revealjs/themes.html#sass-variables).